// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testServer.proto

package so.sao.test.protobuf;

public final class TestServer {
  private TestServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code PhoneType}
   */
  public enum PhoneType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>HOME = 0;</code>
     */
    HOME(0),
    /**
     * <code>WORK = 1;</code>
     */
    WORK(1),
    /**
     * <code>OTHOR = 2;</code>
     */
    OTHOR(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>HOME = 0;</code>
     */
    public static final int HOME_VALUE = 0;
    /**
     * <code>WORK = 1;</code>
     */
    public static final int WORK_VALUE = 1;
    /**
     * <code>OTHOR = 2;</code>
     */
    public static final int OTHOR_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PhoneType valueOf(int value) {
      return forNumber(value);
    }

    public static PhoneType forNumber(int value) {
      switch (value) {
        case 0: return HOME;
        case 1: return WORK;
        case 2: return OTHOR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PhoneType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
            public PhoneType findValueByNumber(int number) {
              return PhoneType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return so.sao.test.protobuf.TestServer.getDescriptor().getEnumTypes().get(0);
    }

    private static final PhoneType[] VALUES = values();

    public static PhoneType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PhoneType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PhoneType)
  }

  public interface AddPhoneToUserRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AddPhoneToUserRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 uid = 1;</code>
     */
    int getUid();

    /**
     * <code>optional .PhoneType phoneType = 2;</code>
     */
    int getPhoneTypeValue();
    /**
     * <code>optional .PhoneType phoneType = 2;</code>
     */
    so.sao.test.protobuf.TestServer.PhoneType getPhoneType();

    /**
     * <code>optional string phoneNumber = 3;</code>
     */
    java.lang.String getPhoneNumber();
    /**
     * <code>optional string phoneNumber = 3;</code>
     */
    com.google.protobuf.ByteString
        getPhoneNumberBytes();
  }
  /**
   * Protobuf type {@code AddPhoneToUserRequest}
   */
  public  static final class AddPhoneToUserRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AddPhoneToUserRequest)
      AddPhoneToUserRequestOrBuilder {
    // Use AddPhoneToUserRequest.newBuilder() to construct.
    private AddPhoneToUserRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddPhoneToUserRequest() {
      uid_ = 0;
      phoneType_ = 0;
      phoneNumber_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AddPhoneToUserRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              uid_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              phoneType_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              phoneNumber_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return so.sao.test.protobuf.TestServer.internal_static_AddPhoneToUserRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return so.sao.test.protobuf.TestServer.internal_static_AddPhoneToUserRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              so.sao.test.protobuf.TestServer.AddPhoneToUserRequest.class, so.sao.test.protobuf.TestServer.AddPhoneToUserRequest.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private int uid_;
    /**
     * <code>optional int32 uid = 1;</code>
     */
    public int getUid() {
      return uid_;
    }

    public static final int PHONETYPE_FIELD_NUMBER = 2;
    private int phoneType_;
    /**
     * <code>optional .PhoneType phoneType = 2;</code>
     */
    public int getPhoneTypeValue() {
      return phoneType_;
    }
    /**
     * <code>optional .PhoneType phoneType = 2;</code>
     */
    public so.sao.test.protobuf.TestServer.PhoneType getPhoneType() {
      so.sao.test.protobuf.TestServer.PhoneType result = so.sao.test.protobuf.TestServer.PhoneType.valueOf(phoneType_);
      return result == null ? so.sao.test.protobuf.TestServer.PhoneType.UNRECOGNIZED : result;
    }

    public static final int PHONENUMBER_FIELD_NUMBER = 3;
    private volatile java.lang.Object phoneNumber_;
    /**
     * <code>optional string phoneNumber = 3;</code>
     */
    public java.lang.String getPhoneNumber() {
      java.lang.Object ref = phoneNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phoneNumber_ = s;
        return s;
      }
    }
    /**
     * <code>optional string phoneNumber = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneNumberBytes() {
      java.lang.Object ref = phoneNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phoneNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uid_ != 0) {
        output.writeInt32(1, uid_);
      }
      if (phoneType_ != so.sao.test.protobuf.TestServer.PhoneType.HOME.getNumber()) {
        output.writeEnum(2, phoneType_);
      }
      if (!getPhoneNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, phoneNumber_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, uid_);
      }
      if (phoneType_ != so.sao.test.protobuf.TestServer.PhoneType.HOME.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, phoneType_);
      }
      if (!getPhoneNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, phoneNumber_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof so.sao.test.protobuf.TestServer.AddPhoneToUserRequest)) {
        return super.equals(obj);
      }
      so.sao.test.protobuf.TestServer.AddPhoneToUserRequest other = (so.sao.test.protobuf.TestServer.AddPhoneToUserRequest) obj;

      boolean result = true;
      result = result && (getUid()
          == other.getUid());
      result = result && phoneType_ == other.phoneType_;
      result = result && getPhoneNumber()
          .equals(other.getPhoneNumber());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid();
      hash = (37 * hash) + PHONETYPE_FIELD_NUMBER;
      hash = (53 * hash) + phoneType_;
      hash = (37 * hash) + PHONENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneNumber().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static so.sao.test.protobuf.TestServer.AddPhoneToUserRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(so.sao.test.protobuf.TestServer.AddPhoneToUserRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AddPhoneToUserRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AddPhoneToUserRequest)
        so.sao.test.protobuf.TestServer.AddPhoneToUserRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return so.sao.test.protobuf.TestServer.internal_static_AddPhoneToUserRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return so.sao.test.protobuf.TestServer.internal_static_AddPhoneToUserRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                so.sao.test.protobuf.TestServer.AddPhoneToUserRequest.class, so.sao.test.protobuf.TestServer.AddPhoneToUserRequest.Builder.class);
      }

      // Construct using so.sao.test.protobuf.TestServer.AddPhoneToUserRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uid_ = 0;

        phoneType_ = 0;

        phoneNumber_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return so.sao.test.protobuf.TestServer.internal_static_AddPhoneToUserRequest_descriptor;
      }

      public so.sao.test.protobuf.TestServer.AddPhoneToUserRequest getDefaultInstanceForType() {
        return so.sao.test.protobuf.TestServer.AddPhoneToUserRequest.getDefaultInstance();
      }

      public so.sao.test.protobuf.TestServer.AddPhoneToUserRequest build() {
        so.sao.test.protobuf.TestServer.AddPhoneToUserRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public so.sao.test.protobuf.TestServer.AddPhoneToUserRequest buildPartial() {
        so.sao.test.protobuf.TestServer.AddPhoneToUserRequest result = new so.sao.test.protobuf.TestServer.AddPhoneToUserRequest(this);
        result.uid_ = uid_;
        result.phoneType_ = phoneType_;
        result.phoneNumber_ = phoneNumber_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof so.sao.test.protobuf.TestServer.AddPhoneToUserRequest) {
          return mergeFrom((so.sao.test.protobuf.TestServer.AddPhoneToUserRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(so.sao.test.protobuf.TestServer.AddPhoneToUserRequest other) {
        if (other == so.sao.test.protobuf.TestServer.AddPhoneToUserRequest.getDefaultInstance()) return this;
        if (other.getUid() != 0) {
          setUid(other.getUid());
        }
        if (other.phoneType_ != 0) {
          setPhoneTypeValue(other.getPhoneTypeValue());
        }
        if (!other.getPhoneNumber().isEmpty()) {
          phoneNumber_ = other.phoneNumber_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        so.sao.test.protobuf.TestServer.AddPhoneToUserRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (so.sao.test.protobuf.TestServer.AddPhoneToUserRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int uid_ ;
      /**
       * <code>optional int32 uid = 1;</code>
       */
      public int getUid() {
        return uid_;
      }
      /**
       * <code>optional int32 uid = 1;</code>
       */
      public Builder setUid(int value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 uid = 1;</code>
       */
      public Builder clearUid() {
        
        uid_ = 0;
        onChanged();
        return this;
      }

      private int phoneType_ = 0;
      /**
       * <code>optional .PhoneType phoneType = 2;</code>
       */
      public int getPhoneTypeValue() {
        return phoneType_;
      }
      /**
       * <code>optional .PhoneType phoneType = 2;</code>
       */
      public Builder setPhoneTypeValue(int value) {
        phoneType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .PhoneType phoneType = 2;</code>
       */
      public so.sao.test.protobuf.TestServer.PhoneType getPhoneType() {
        so.sao.test.protobuf.TestServer.PhoneType result = so.sao.test.protobuf.TestServer.PhoneType.valueOf(phoneType_);
        return result == null ? so.sao.test.protobuf.TestServer.PhoneType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .PhoneType phoneType = 2;</code>
       */
      public Builder setPhoneType(so.sao.test.protobuf.TestServer.PhoneType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        phoneType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .PhoneType phoneType = 2;</code>
       */
      public Builder clearPhoneType() {
        
        phoneType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object phoneNumber_ = "";
      /**
       * <code>optional string phoneNumber = 3;</code>
       */
      public java.lang.String getPhoneNumber() {
        java.lang.Object ref = phoneNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phoneNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string phoneNumber = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneNumberBytes() {
        java.lang.Object ref = phoneNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phoneNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string phoneNumber = 3;</code>
       */
      public Builder setPhoneNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phoneNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string phoneNumber = 3;</code>
       */
      public Builder clearPhoneNumber() {
        
        phoneNumber_ = getDefaultInstance().getPhoneNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional string phoneNumber = 3;</code>
       */
      public Builder setPhoneNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phoneNumber_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:AddPhoneToUserRequest)
    }

    // @@protoc_insertion_point(class_scope:AddPhoneToUserRequest)
    private static final so.sao.test.protobuf.TestServer.AddPhoneToUserRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new so.sao.test.protobuf.TestServer.AddPhoneToUserRequest();
    }

    public static so.sao.test.protobuf.TestServer.AddPhoneToUserRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddPhoneToUserRequest>
        PARSER = new com.google.protobuf.AbstractParser<AddPhoneToUserRequest>() {
      public AddPhoneToUserRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AddPhoneToUserRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AddPhoneToUserRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddPhoneToUserRequest> getParserForType() {
      return PARSER;
    }

    public so.sao.test.protobuf.TestServer.AddPhoneToUserRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddPhoneToUserResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AddPhoneToUserResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool result = 1;</code>
     */
    boolean getResult();
  }
  /**
   * Protobuf type {@code AddPhoneToUserResponse}
   */
  public  static final class AddPhoneToUserResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AddPhoneToUserResponse)
      AddPhoneToUserResponseOrBuilder {
    // Use AddPhoneToUserResponse.newBuilder() to construct.
    private AddPhoneToUserResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddPhoneToUserResponse() {
      result_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AddPhoneToUserResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              result_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return so.sao.test.protobuf.TestServer.internal_static_AddPhoneToUserResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return so.sao.test.protobuf.TestServer.internal_static_AddPhoneToUserResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              so.sao.test.protobuf.TestServer.AddPhoneToUserResponse.class, so.sao.test.protobuf.TestServer.AddPhoneToUserResponse.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private boolean result_;
    /**
     * <code>optional bool result = 1;</code>
     */
    public boolean getResult() {
      return result_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != false) {
        output.writeBool(1, result_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, result_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof so.sao.test.protobuf.TestServer.AddPhoneToUserResponse)) {
        return super.equals(obj);
      }
      so.sao.test.protobuf.TestServer.AddPhoneToUserResponse other = (so.sao.test.protobuf.TestServer.AddPhoneToUserResponse) obj;

      boolean result = true;
      result = result && (getResult()
          == other.getResult());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getResult());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static so.sao.test.protobuf.TestServer.AddPhoneToUserResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(so.sao.test.protobuf.TestServer.AddPhoneToUserResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AddPhoneToUserResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AddPhoneToUserResponse)
        so.sao.test.protobuf.TestServer.AddPhoneToUserResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return so.sao.test.protobuf.TestServer.internal_static_AddPhoneToUserResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return so.sao.test.protobuf.TestServer.internal_static_AddPhoneToUserResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                so.sao.test.protobuf.TestServer.AddPhoneToUserResponse.class, so.sao.test.protobuf.TestServer.AddPhoneToUserResponse.Builder.class);
      }

      // Construct using so.sao.test.protobuf.TestServer.AddPhoneToUserResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        result_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return so.sao.test.protobuf.TestServer.internal_static_AddPhoneToUserResponse_descriptor;
      }

      public so.sao.test.protobuf.TestServer.AddPhoneToUserResponse getDefaultInstanceForType() {
        return so.sao.test.protobuf.TestServer.AddPhoneToUserResponse.getDefaultInstance();
      }

      public so.sao.test.protobuf.TestServer.AddPhoneToUserResponse build() {
        so.sao.test.protobuf.TestServer.AddPhoneToUserResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public so.sao.test.protobuf.TestServer.AddPhoneToUserResponse buildPartial() {
        so.sao.test.protobuf.TestServer.AddPhoneToUserResponse result = new so.sao.test.protobuf.TestServer.AddPhoneToUserResponse(this);
        result.result_ = result_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof so.sao.test.protobuf.TestServer.AddPhoneToUserResponse) {
          return mergeFrom((so.sao.test.protobuf.TestServer.AddPhoneToUserResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(so.sao.test.protobuf.TestServer.AddPhoneToUserResponse other) {
        if (other == so.sao.test.protobuf.TestServer.AddPhoneToUserResponse.getDefaultInstance()) return this;
        if (other.getResult() != false) {
          setResult(other.getResult());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        so.sao.test.protobuf.TestServer.AddPhoneToUserResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (so.sao.test.protobuf.TestServer.AddPhoneToUserResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean result_ ;
      /**
       * <code>optional bool result = 1;</code>
       */
      public boolean getResult() {
        return result_;
      }
      /**
       * <code>optional bool result = 1;</code>
       */
      public Builder setResult(boolean value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool result = 1;</code>
       */
      public Builder clearResult() {
        
        result_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:AddPhoneToUserResponse)
    }

    // @@protoc_insertion_point(class_scope:AddPhoneToUserResponse)
    private static final so.sao.test.protobuf.TestServer.AddPhoneToUserResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new so.sao.test.protobuf.TestServer.AddPhoneToUserResponse();
    }

    public static so.sao.test.protobuf.TestServer.AddPhoneToUserResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddPhoneToUserResponse>
        PARSER = new com.google.protobuf.AbstractParser<AddPhoneToUserResponse>() {
      public AddPhoneToUserResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AddPhoneToUserResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AddPhoneToUserResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddPhoneToUserResponse> getParserForType() {
      return PARSER;
    }

    public so.sao.test.protobuf.TestServer.AddPhoneToUserResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddPhoneToUserRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddPhoneToUserRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddPhoneToUserResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddPhoneToUserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020testServer.proto\"X\n\025AddPhoneToUserRequ" +
      "est\022\013\n\003uid\030\001 \001(\005\022\035\n\tphoneType\030\002 \001(\0162\n.Ph" +
      "oneType\022\023\n\013phoneNumber\030\003 \001(\t\"(\n\026AddPhone" +
      "ToUserResponse\022\016\n\006result\030\001 \001(\010**\n\tPhoneT" +
      "ype\022\010\n\004HOME\020\000\022\010\n\004WORK\020\001\022\t\n\005OTHOR\020\0022Q\n\014Ph" +
      "oneService\022A\n\016addPhoneToUser\022\026.AddPhoneT" +
      "oUserRequest\032\027.AddPhoneToUserResponseB\026\n" +
      "\024so.sao.test.protobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AddPhoneToUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AddPhoneToUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddPhoneToUserRequest_descriptor,
        new java.lang.String[] { "Uid", "PhoneType", "PhoneNumber", });
    internal_static_AddPhoneToUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AddPhoneToUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddPhoneToUserResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
